# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - stock-angular

on:
  push:
    branches:
      - azure-pipelines
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_0e6dce9558b74cf681fe2c1af86bb13b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4f4cd3f6adfc4b199b8f10aec144d1fe }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_0e6dce9558b74cf681fe2c1af86bb13b }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'stock-angular'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c6f57ba9cdc74a2fa45ce0e204dc0ba2 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_0e6dce9558b74cf681fe2c1af86bb13b }}/appsvc/staticsite:${{ github.sha }}'